project_id = "adlftnqdeltcbdqgibsr"

[functions.wendy-analyze-journal]
verify_jwt = true

[functions.wendy-chat]
verify_jwt = true

[functions.generate-invite-code]
verify_jwt = true

[functions.generate-avatar]
verify_jwt = true

[functions.send-notifications]
verify_jwt = false